# Site settings
title: Conference Diversity 101
tag_text: Do Better at Conference Diversity
description: Diversity at your event matters. Learn how to do better.

# Build settings
markdown: kramdown

exclude: ["README.md"]
