# Site settings
title: Conference Diversity
tag_text: Do better at conference diversity
description: Diversity at your event matters. Learn how to do better.

# Build settings
markdown: kramdown

exclude: ["README.md"]
